layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Wolfram Language
    web_url: http://wolfram.com
    image_url: http://www.wolfram.com/language/img/wolfram-language-logo.png

  - name: Emacs
    web_url: https://www.gnu.org/software/emacs/
    image_url: https://www.gnu.org/software/emacs/images/emacs.png

  - name: Programming Language Thoery
    web_url: https://en.wikipedia.org/wiki/Programming_language_theory
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Lambda_lc.svg/640px-Lambda_lc.svg.png?1558911654187
